apiVersion: batch/v1
kind: Job
metadata:
  name: batch-job
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app: batch-job
    spec:
      restartPolicy: OnFailure
      containers:
      - name: main
        image: ubuntu
        command: ['expr','5','+','3']
