apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-name
  name: pod-name
spec:
  containers:
  - image: nginx
    name: pod-name
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
