apiVersion: apps/v1
kind: Deployment
metadata:
  name: assignment-deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: front-end
      rel: stable
  template:
    metadata:
      name: assignment-pod
      labels:
        app: front-end
        rel: stable
    spec:
      containers:
      - name: aamirpinger-helloworld-container
        image: aamirpinger/helloworld
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 12
          timeoutSeconds: 6
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 50
          timeoutSeconds: 4
          failureThreshold: 4
          periodSeconds: 8
---
apiVersion: v1
kind: Service
metadata:
  name: assignment-svc
spec:
  type: NodePort
  selector:
    app: front-end
    rel: stable
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
