apiVersion: v1
kind: Pod
metadata:
  name: emptydir-pod
spec:
  containers:
  - image: luksa/fortune
    env:
    - name: POD_NAME228
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: POD_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: SERVICE_ACCOUNT
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.serviceAccountName
    - name: CONTAINER_CPU_REQUEST_MILLICORES
      valueFrom:
        resourceFieldRef:
          divisor: 1m
          resource: requests.cpu
    - name: CONTAINER_MEMORY_LIMIT_KIBIBYTES
      valueFrom:
        resourceFieldRef:
          divisor: 1Ki
          resource: limits.memory
    - name: INITIAL_SLEEP_INTERVAL
      valueFrom:
        configMapKeyRef:
          name: special-cm
          key: special.sleep-interval
#    args: ["$(INITIAL_SLEEP_INTERVAL)"]
    - name: SLEEP_TIME
      valueFrom:
        configMapKeyRef:
          name: special-cm
          key: special.sleepTime
#    args: ["$(SLEEP_TIME)"]
    envFrom:
    - configMapRef:
        name: special-cm
    name: html-generator
    volumeMounts:
    - name: html
      mountPath: /var/htdocs
  - image: nginx:alpine
    name: web-server
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
      readOnly: true
    ports:
    - containerPort: 80
      protocol: TCP 
  volumes:
  - name: html
    emptyDir: 
      medium: Memory
