apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: kubia-rs-match-exp
spec:
  replicas: 3
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
      - name: kubia-rs-match-exp-container
        image: nginx:alpine
