apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
  namespace: my-ns
spec:
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: storage-1
  hostPath:
    path: /tmp/pv

