apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
  namespace: my-ns
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: storage-1

