apiVersion: v1
kind: Service
metadata:
  name: svc-1
spec:
  type: NodePort
  selector:
    app: front-end
  ports:
  - port: 8080
    name: http-svc-port
    targetPort: http
    protocol: TCP
  - port: 8090
    name: https-svc-port
    targetPort: https
    protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    app: front-end
spec:
  containers:
  - name: nginx-cont
    image: nginx
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
    - containerPort: 82
      name: https
      protocol: TCP

