apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100M
  hostPath:
    path: /tmp/pv
  storageClassName: abc
  persistentVolumeReclaimPolicy: Delete  # can be Recycle or Retain (retain is default)
