apiVersion: v1
kind: Namespace
metadta:
  name: my-ns
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv001
  namespace: my-ns
spec:
  accessModes:
  - ReadWriteOnce
  capacity: 
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: storage-1
  claimRef: pvc001
---
apiVersion: v1
kind: PersistenVolumeClaim
metadata:
  name: pvc001
  namespace: my-ns
spec:
  accessModes:
  - ReadWriteOnce
  requests:
    storage: 500Mi
  storageClassName: storage-1
---
apiVersin: apps/v1beta1
kind: Deployment
metadata:
  namespace: my-ns
  name: depl001
spec:
  replicas: 5
  template:
    metadata:
      name: depl001-pod
    spec:
      containers:
      - name: depl001-cont
        image: aamirpinger/helloworld
