apiVersion: v1
kind: Service
metadata:
  name: nodeport
spec:
  type: NodePort
  selector:
    app: nginx
    environment: prod
  ports:
  - nodePort: 32410
    protocol: TCP
    port: 80
    targetPort: 80
